### ISSUE TITLE
URL : Add setter

### ISSUE THREAD

**Issue by Gmulti** [weglot/weglot-php#33]
**Is this a BUG REPORT or FEATURE REQUEST?**: Feature

**What happened**:
Add a setter to the URL class. We may need it if we want to manage the URL base ourselves according to integrations.

**How to reproduce it (some code is appreciated)**:
```
$url = new Url();
$url->setBaseUrl('/other-website/');
```

**Comment by Korbeil** [comment]
`$baseUrl` is only used internally and should not be used elsewhere.

Was related to #33 but since it's fixed I'm closing this one too.
