### ISSUE TITLE
Ignore Node doesn't work when there is a class on the node

### ISSUE THREAD

**Issue by remyberda** [weglot/weglot-php#40]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug

**What happened**:
When we have a ignored node that has a class, only the closing tag is escape

**Comment by remyberda** [comment]
Sur WordPress, voici la fonction que j'ai utilisé:
```php
function ignoreNodes($dom)
    {

        foreach (self::NODES_TO_IGNORE as $n) {

            $openRegex = "#<$n([^>]*)?>#";
            $closeRegex = "</$n>";
            
            $dom = preg_replace($openRegex, htmlentities("<$n$1>"), $dom);
            $dom = str_replace($closeRegex, htmlentities($closeRegex), $dom);
        }
       return $dom;
    }
```

**Comment by Korbeil** [comment]
We're not affected by this since we replace nodes based on `\SimpleHtmlDom\simple_html_dom_node` class and this class make all the work to keep context contents.
