### ISSUE TITLE
URL with a port doesn't work

### ISSUE THREAD

**Issue by Gmulti** [weglot/weglot-php#41]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

**What happened**: The port of an URL doesn't seem to be supported when trying to retrieve URLs

**How to reproduce it (some code is appreciated)**:
```php
$weglotUrl = new Url(
      'http://weglotd7.local:8080/es/node',
      'en',
      ['fr', 'es']
 );

$weglotUrl->getForLanguage('fr'); //  string(29) "http://weglotd7.local/fr/node"

```

**Environment**:
- Library version :  latest
- PHP version  :  5.4

**Comment by Gmulti** [comment]
Detect URL details: 
```php 

object(Weglot\Util\Url)#51 (8) { ["url":protected]=> string(34) "http://weglotd7.local:8080/es/node" ["host":protected]=> string(21) "http://weglotd7.local" ["baseUrl":protected]=> string(5) "/node" ["allUrls":protected]=> NULL ["default":protected]=> string(2) "en" ["languages":protected]=> array(3) { [0]=> string(2) "en" [1]=> string(2) "fr" [2]=> string(2) "es" } ["pathPrefix":protected]=> string(0) "" ["excludedUrls":protected]=> array(0) { } }
```

**Comment by Korbeil** [comment]
Fixed with https://github.com/weglot/weglot-php/commit/311932588c483f9c78fe7858c0d233d896c86f2c & tag [`v0.5.1`](https://github.com/weglot/weglot-php/tree/0.5.1)
