### ISSUE TITLE
Bug : URL default is not good

### ISSUE THREAD

**Issue by Gmulti** [weglot/weglot-php#42]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

**What happened**: When I start with a translated URL and I want to get the default language URL, I don't get the correct one.

**How to reproduce it (some code is appreciated)**:
```php
$weglotUrl = new Url(
      'http://weglotd7.local:8080/es/node',
      'en',
      ['fr', 'es']
 );

$weglotUrl->getForLanguage('en'); //  string(29) "http://weglotd7.local/en/node"
```

**Anything else we need to know?**:
Here's what we should get: 
```php
$weglotUrl = new Url(
      'http://weglotd7.local:8080/es/node',
      'en',
      ['fr', 'es']
 );

$weglotUrl->getForLanguage('en'); //  string(29) "http://weglotd7.local/node"
```

**Environment**:
- Library version : 0.5.1
- PHP version : 5.4

**Comment by Korbeil** [comment]
Running same `Url` instance as described on `develop` branch gives me:
```
/Users/bleduc/Sites/weglot/weglot-php/examples/url-test/run.php:13:
string(31) "http://weglotd7.local:8080/node"
```

**Comment by Gmulti** [comment]
Maybe with this information ?
<img width="584" alt="example" src="https://user-images.githubusercontent.com/5682535/40660810-678e5a2e-6352-11e8-8d6f-201323a832ab.png">
