### ISSUE TITLE
Not make an exception on Client Translate

### ISSUE THREAD

**Issue by Gmulti** [weglot/weglot-php#43]
**Is this a BUG REPORT or FEATURE REQUEST?**: Feature / Improvement

**What happened**:
When there is an API error, it should be possible to retrieve this error message or put it in the logs.
Otherwise it can be displayed on customer sites.

https://github.com/weglot/weglot-php/blob/764e83212173cc051c7e6e05beded039bad9a973/src/Client/Endpoint/Translate.php#L180
**What you expected to happen**:

**How to reproduce it (some code is appreciated)**:
Simulating an API error

**Environment**:
- Library version : latest
- PHP version : 5.4

**Comment by Korbeil** [comment]
What can I suggest is, when we don't have an array, check in body if there is a message and use it if there one. But I still prefer using exception (since you can catch it and handle it if needed).

@Gmulti this sounds ok for you ?
