### ISSUE TITLE
Node not translated

### ISSUE THREAD

**Issue by remyberda** [weglot/weglot-php#54]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**What happened**:
When sending this input:

```html
<p><em>This is the best sentence</em> which is fun</p>
<aside data-wg-notranslate><ul><li>ok</li><ul></aside>
<p>This is the meta description of this page</p>
```

last node is not translate

**What you expected to happen**:
The last not should also be translated

**How to reproduce it (some code is appreciated)**:

**Anything else we need to know?**:

**Environment**:
- Library version 
- PHP version

**Comment by Korbeil** [comment]
It seems that `simple_html_dom` isn't giving `<p>` tags with `text` alias.

**Comment by remyberda** [comment]
Some things I have noted:

- `Text.php`  should have ` WORD_TYPE = WordType::TEXT;`
-  `input:not([type])`  should be remove in `Placeholder.php`, it doesn't seem to work in simple_html_dom

**Comment by Korbeil** [comment]
@remyberda both notes are fixed in the issue branch (will come with the PR)

**Comment by remyberda** [comment]
- La fonction `$checkers = $this->getCheckers();` renvoie aussi la classe `\Weglot\Parser\Check\Dom\AbstractDomChecker`. Il faudrait que ça renvoie que les vrais checkers, pour éviter d'avoir un selecteur nul ensuite

**Comment by Korbeil** [comment]
Fixed , it was something working before, but we changed `AbstractDomChecker` class name from `AbstractChecker`

**Comment by Korbeil** [comment]
About this issue, after deep searches, it isn't an issue at all, it's just wrong DOM formatting.

You provided:
```html
<p><em>This is the best sentence</em> which is fun</p>
<aside data-wg-notranslate><ul><li>ok</li><ul></aside>
<p>This is the meta description of this page</p>
```

But we can see at second line that the `<ul>` element is open 2 times and never closed. Like that, `simple_html_dom` is going crazy and thinks everything behind is a child from the first `<ul>` and also a child of the `<aside>` that have the `data-wg-notranslate` attribute.
