### ISSUE TITLE
Ignore nodes not working when there is a class

### ISSUE THREAD

**Issue by remyberda** [weglot/weglot-php#56]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**What happened**:
When in Profile 2 (API  key length = 36), there is a bug with escaped node.

When passing
`<p><strong>C'est un test</strong> qui va fonctionner</p>`=> OK

When passing
`<p><strong class="test">C'est un test</strong> qui va fonctionner</p>` => KO
L' API sépare le texte. Le pb est du à ignored Nodes qui match exactement `<strong>`

**Solution**
Sur WP, on avait résolu ça:

```php
self::$NODES_TO_IGNORE = array("strong","em","abbr","acronym","b","bdo","big","cite","kbd","q","small","sub","sup");
function ignoreNodes($dom)
 {
        foreach (self::$NODES_TO_IGNORE as $n) {

            $openRegex = "#<$n( [^>]*)?>#";
            $closeRegex = "</$n>";

            $dom = preg_replace($openRegex, "&lt;$n$1&gt;", $dom);
            $dom = str_replace($closeRegex, "&lt;/$n&gt;", $dom);
        }

        return $dom;
}
```

**Comment by Korbeil** [comment]
After quick test, I'm not able to reproduce the bug.
Which version of the Developer Kit was used ? Which version of PHP ?

**Comment by Korbeil** [comment]
After quick review with @remyberda, It seems that it's separated in two parts on the translation list (when it should be only in one part with `$ignoredNodes = true;`)
