### ISSUE TITLE
Be able to translate a PHP array

### ISSUE THREAD

**Issue by Gmulti** [weglot/weglot-php#68]
**Is this a BUG REPORT or FEATURE REQUEST?**: Feature request

**What happened**: In different integrations, one may need to send a array that contains HTML and translate these different entries

**How to reproduce it (some code is appreciated)**:
```php
<?php

$array = array(
      "view_cart" => "<a href='https://example.com'>View cart</a>",
      "items" => array(
             "salad" => "<h1>An amazing salad</h1><a href='https://example.com'>Click here please</a>"
       )
);
```

**Environment**:
- PHP version : Minimum 5.4

**Comment by remyberda** [comment]
Done in 0.5.27
