### ISSUE TITLE
&nbsp; makes the library crash

### ISSUE THREAD

**Issue by remyberda** [weglot/weglot-php#69]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG

**What happened**:
When you send `<p>&nbsp;</p>` , it crashes:

![capture d ecran 2018-07-05 a 15 05 58](https://user-images.githubusercontent.com/22366468/42324929-fb9c28ca-8064-11e8-938e-98bb9dbcc796.png)

**What you expected to happen**:
It should answer `<p>&nbsp;</p>`

**How to reproduce it (some code is appreciated)**:

```php
<?php

require_once __DIR__. '/weglot-php/vendor/autoload.php';

use Weglot\Client\Client;
use Weglot\Parser\Parser;
use Weglot\Parser\ConfigProvider\ManualConfigProvider;
use Weglot\Client\Api\Enum\BotType;

// Url to parse
$url = 'https://weglot.com/documentation/getting-started';

// Config manually
$config = new ManualConfigProvider($url, BotType::HUMAN);

// Client
$client = new Client('wg_XXXX');
$parser = new Parser($client, $config);

$contents = <<<EOT


<p>&nbsp;</p>

EOT;

// Run the Parser

$translatedContent = $parser->translate($contents, 'en', 'fr');



// dumping returned object
echo $translatedContent;
```

**Comment by Korbeil** [comment]
Fixed: https://github.com/weglot/weglot-php/commit/0f3cf9a4b3b8a836d717afc5ca9a130de067023e
