### ISSUE TITLE
doctype and html tag are removed

### ISSUE THREAD

**Issue by remyberda** [weglot/weglot-php#72]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG

**What happened**:
When you send a full HTML page, it removes the `<!DOCTYPE html>` and `html` tag. It should return it, like in the 0.5.8.

It returns:

```html
<head>
</head>

<body>

</body>
```

**What you expected to happen**:

**How to reproduce it (some code is appreciated)**:
```php
<?php

require_once __DIR__. '/weglot-php/vendor/autoload.php';

use Weglot\Client\Client;
use Weglot\Parser\Parser;
use Weglot\Parser\ConfigProvider\ManualConfigProvider;
use Weglot\Client\Api\Enum\BotType;

// Url to parse
$url = 'http://wordpress/sample-page2/';

// Config manually
$config = new ManualConfigProvider($url, BotType::HUMAN);

// Client
$client = new Client('wg_XXX');
$parser = new Parser($client, $config);

$contents = <<<EOT

<!DOCTYPE html>
<html lang="en" prefix="og: http://ogp.me/ns#">
<head>
</head>

<body>

</body>
</html>

EOT;

// Run the Parser

$translatedContent = $parser->translate($contents, 'en', 'fr');



// dumping returned object
echo $translatedContent;
```

**Comment by Korbeil** [comment]
Fixed https://github.com/weglot/weglot-php/commit/86b7c270bd763aec50f9fd00322ff491f51c2579

We do not support doctypes atm, do we really to ? @remyberda

**Comment by Korbeil** [comment]
Fixed https://github.com/weglot/weglot-php/commit/11fa67c03d11c7570ecbcbdb8766da96314436db & https://github.com/weglot/weglot-php/commit/1279086094dc08e39cdbaa69e2f140aef48975a5
