### ISSUE TITLE
Bug when setLocale is en_US with some special char

### ISSUE THREAD

**Issue by remyberda** [weglot/weglot-php#75]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG

**What happened**:
The lib is returning an error with some character only when we have:
`setlocale(LC_ALL, "en_US.UTF-8");`

**What you expected to happen**:
No error

**How to reproduce it (some code is appreciated)**:
```
<?php

require_once __DIR__. '/weglot-php/vendor/autoload.php';

use Weglot\Client\Client;
use Weglot\Parser\Parser;
use Weglot\Parser\ConfigProvider\ManualConfigProvider;
use Weglot\Client\Api\Enum\BotType;

// Url to parse
$url = 'https://weglot.com/documentation/getting-started';

// Config manually
$config = new ManualConfigProvider($url, BotType::HUMAN);

// Client
$client = new Client('wg_XXXXX');
$parser = new Parser($client, $config);

setlocale(LC_ALL, "en_US.UTF-8"); //TRY COMMENTING THIS AND IT WILL WORK

$contents = <<<EOT


<div>Αποστολές – Πληρωμές</div>


EOT;

// Run the Parser

$translatedContent = $parser->translate($contents, 'en', 'fr');



// dumping returned object
echo $translatedContent;
````
**Anything else we need to know?**:
I believe it's linked to https://github.com/silverstripe/silverstripe-framework/issues/7132
When commenting line 77 of AbstractCrawlerAfterListener.php
`$fixed = preg_replace('/\s+/', ' ', $fixed);`
It works...

**Comment by remyberda** [comment]
From : https://github.com/silverstripe/silverstripe-framework/issues/7132

A quick fix is to replace 
`$fixed = preg_replace('/\s+/', ' ', $fixed);`
by
`$fixed = preg_replace('/\s+/u', ' ', $fixed);`

**Comment by Korbeil** [comment]
Fixed https://github.com/weglot/weglot-php/commit/b8578616a275664e430a64776d178e4b3ff5d530
