### ISSUE TITLE
Do no trim words

### ISSUE THREAD

**Issue by remyberda** [weglot/weglot-php#77]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG

**What happened**:
When we send to the Lib:
`<p>As a new WordPress user, you should go to <a href="http://wordpress/wp-admin/">your dashboard</a> to delete this page and create new pages for your content. Have fun!</p>`

We got this:

`<p>En tant que nouvel utilisateur de WordPress, vous devriez aller à<a href="http://wordpress/wp-admin/">votre tableau de bord</a>pour supprimer cette page et créer de nouvelles pages pour votre contenu. Amusez-vous!</p>`

=> The sentence is missing space before and after the link

**What you expected to happen**:
We need to send spaces to the API. The API is handling this well.

**How to reproduce it (some code is appreciated)**:

**Anything else we need to know?**:
A solution is to remove `$fixed = Text::fullTrim($value);`

**Comment by Korbeil** [comment]
Fixed by https://github.com/weglot/weglot-php/commit/67d935b17ce50a522df1242df23a3b0e30f67e30
