### ISSUE TITLE
No transformation of HTML characters

### ISSUE THREAD

**Issue by Gmulti** [weglot/weglot-php#78]
**Is this a BUG REPORT or FEATURE REQUEST?**: Bug

**What happened**: HTML characters are not "re-transformed".

**What you expected to happen**:
`Built with Storefront & WooCommerce.` is translate by : `Construit avec vitrine &amp; WooCommerce.`

**Environment**:
- Library version : 0.6.2
- PHP version : 5.4

**Comment by Korbeil** [comment]
Fixed by https://github.com/weglot/weglot-php/commit/70193f747fda575398db346efb677ebb4b3c202a
