### ISSUE TITLE
Trim Exclude URL and Exclude blocks

### ISSUE THREAD

**Issue by remyberda** [weglot/weglot-php#79]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Feature request

**What happened**:
This should be the same:
```
 .myclass
.myclass
.myclass 
```

Same for exclude URL

**Comment by Korbeil** [comment]
Fixed with https://github.com/weglot/weglot-php/commit/0b2de984fc4062e293b0159d379ee89cd89cee9b
