### ISSUE TITLE
ignored nodes appear escaped when inside exclude block

### ISSUE THREAD

**Issue by remyberda** [weglot/weglot-php#85]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG

**What happened**:
When you send an ignored node to the parser, which is inside a excluded block, it gets escaped.

In my example, I excluded class `.test`

I tried sending:
`<p class="test">This is <b>cool</b></p>`

I got this:
`<p class="test" data-wg-notranslate="">This is &lt;b&gt;cool&lt;/b&gt;</p>`

I expect this:
`<p class="test" data-wg-notranslate="">This is <b>cool</b></p>`

**How to reproduce it (some code is appreciated)**:
```php
<?php

require_once __DIR__. '/weglot-php/vendor/autoload.php';

use Weglot\Client\Client;
use Weglot\Parser\Parser;
use Weglot\Parser\ConfigProvider\ManualConfigProvider;
use Weglot\Client\Api\Enum\BotType;

// Url to parse
$url = 'https://weglot.com/documentation/getting-started';

// Config manually
$config = new ManualConfigProvider($url, BotType::HUMAN);

// Client
$client = new Client('wg_XXXX');
$parser = new Parser($client, $config);

//$contents = file_get_contents('content.txt');
$contents = <<<EOF

    <p class="test">This is <b>cool</b></p>

EOF;

$parser->setExcludeBlocks(array('.test'));

// Run the Parser

$translatedContent = $parser->translate($contents, 'en', 'fr');



// dumping returned object
echo $translatedContent;
```

**Comment by Korbeil** [comment]
After trying, no error on both `0.6.3` & `0.5.9`

More details on how I could reproduce the bug ?

**Comment by Korbeil** [comment]
Fixed in https://github.com/weglot/weglot-php/commit/c0440916345979723178c464cc3ee57eda00ee44

**Comment by remyberda** [comment]
The solution is a bit too hard as it will unescaped all `&gt;` in the DOM

Here is what we can do, adding code in `handle` in file DomCheckerProvider.
That way, we say to unescape only when we are in the case of a node that is not sent to the API

<img width="737" alt="capture d ecran 2018-07-19 a 14 50 43" src="https://user-images.githubusercontent.com/22366468/42943572-6b66b86a-8b63-11e8-9e50-b3e279fecb0a.png">

**Comment by remyberda** [comment]
With code:

```php
} else {
                    if (strpos($node->$property, '&gt;') !== false || strpos($node->$property, '&lt;') !== false) {
                        $node->$property = str_replace(['&lt;', '&gt;'], ['<', '>'], $node->$property);
                    }
                }
```

**Comment by Korbeil** [comment]
Fixed.
