### ISSUE TITLE
Curl version not found

### ISSUE THREAD

**Issue by Gmulti** [weglot/weglot-php#86]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

**What happened**: On some installations, namespace management is not necessarily good. This causes an error on the cURL functions 

**Anything else we need to know?**:

Example : `PHP Fatal error: Call to undefined function Weglot\\Client\\HttpClient\\curl_version() in /var/www/exatec/wp-content/plugins/weglot/vendor/weglot/weglot-php/src/Client/HttpClient/CurlClient.php `

**Environment**:
- Library version : 0.5.9
- PHP version : 5.6

**Comment by Korbeil** [comment]
Patch is ready, I'm just waiting feedback from your side before updating the library with it.

**Comment by Gmulti** [comment]
It is necessary to keep the fix by prevention.
Otherwise, the initial problem finally came from the client's server configuration
